---
- name: Playbook to install python 3
  hosts: test_server
  become: true
  gather_facts: false

  tasks:
    - name: Install python and pip
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python3-pip
        - python3

    - name: Update repositories cache
      apt: update-cache=yes

      vars:
        ansible_python_interpreter: /usr/bin/python3
